[package]
name = "termusic-playback"
description = "playback library to support termusic." 
version.workspace = true 
authors.workspace = true 
edition.workspace = true
license.workspace = true 
repository.workspace = true 
homepage.workspace = true 
keywords.workspace = true 
categories.workspace = true 


[lib]
name = "termusicplayback"
path = "src/lib.rs"
doctest = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
termusic-lib.workspace = true # {path = "../lib/"}
cpal.workspace = true
anyhow.workspace = true 
bincode.workspace = true
thiserror.workspace = true 
glib = { version="0.17", optional = true }
gstreamer = { version="0.20", optional = true}
lazy_static.workspace = true
libmpv-sys  = { version = "3", optional = true }
log.workspace = true # = "0.4"
lovely_env_logger.workspace = true # = "0.6"
pathdiff.workspace = true #  = { version = "0.2", features = ["camino"] }
rand.workspace = true #  = "0.8"
symphonia.workspace = true #  = { version = "0.5.1",  features = ["aac","mp3","isomp4","alac"]}
ureq.workspace = true #   = "2"
serde.workspace = true
souvlaki.workspace = true
tokio.workspace = true
parking_lot.workspace = true
discord-rich-presence.workspace = true

[features]
# default = []
# left for debug
default = ["mpv"]
# default = ["mpv"]
# cover = []
gst = ["gstreamer","glib"]
mpv = ["libmpv-sys"]


[dev-dependencies]
pretty_assertions = "1"
# anyhow = "1"
# hound = "3.4"
# ringbuf = "0.3"
# clap = { version = "3.1", default-features = false, features = ["std"] }

