[package]
name = "termusic"
version = "0.7.10"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Terminal Music and Podcast Player written in Rust. Can download music from youtube(netease/migu/kugou) and then embed lyrics and album photos into mp3/m4a/flac/wav/ogg vorbis files."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui","music","youtube","podcast"]
categories = ["command-line-interface","command-line-utilities", "multimedia::audio"]
readme = "README.md"

[workspace]

members = [
    "daemon",
    "lib",
]

[workspace.package]
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Terminal Music and Podcast Player written in Rust. Can download music from youtube(netease/migu/kugou) and then embed lyrics and album photos into mp3/m4a/flac/wav/ogg vorbis files."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui","music","youtube","podcast"]
categories = ["command-line-interface","command-line-utilities", "multimedia::audio"]
readme = "./README.md"
version = "0.7.10"

[workspace.dependencies]
anyhow = "1.0"
base64 = "0.21"
clap = { version="4", features = ["derive"] }
# cpal = "0.13"
thiserror = "1.0.2"
dirs = "5.0"
discord-rich-presence = { version="0.2"}
figment = { version="0.10", features = ["toml"]}
glib = { version="0.17" }
gstreamer = { version="0.20"}
hex = "0.4"
id3 = "1"
image = "0.24"
include_dir = "0.7"
lazy_static = "1.4"
# lexopt = "0.2"
libaes = "0.6"
libmpv-sys = { version = "3" }
# libmpv = { version = "2",  optional = true}
log = "0.4"
lovely_env_logger = "0.6"
lofty = "0.12"
md5 = "0.7"
num-bigint = "0.4"
pathdiff = { version = "0.2", features = ["camino"] }
pinyin = "0.9"
quick-xml = "0.28"
rand = "0.8"
regex = "^1.5.5"
rusqlite = { version = "0.29", features = ["bundled"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3"
souvlaki = { version = "0.6" }
symphonia = { version = "0.5.1",  features = ["aac","mp3","isomp4","alac"]}
# tempfile = { version = "3", optional = true}
toml = "0.7"
# tuirealm = { path = "../tui-realm", features = ["serialize"] }
# tui-realm-stdlib = {path = "../tui-realm-stdlib"}
# tui-realm-treeview = { path = "../tui-realm-treeview"}
tuirealm = { version = "1", features = ["serialize"] }
tui-realm-stdlib = "1"
tui-realm-treeview = "1"
unicode-width = "^0.1.8"
ureq = "2"
urlencoding = "2"
# viuer = { version = "0.6", features = ["sixel"] }
viuer = "0.6"
yaml-rust = "^0.4.5"
ytd-rs = { version = "0.1", features = ["yt-dlp"]}
walkdir = "2"
wildmatch = "2"
opml = "1"
chrono = "^0.4.23"
rss = "2"
rfc822_sanitizer = "0.3" 
ahash = "^0.8"
semver = "^1"
escaper = "0.1.1"
textwrap = "0.16"
bytes = "1"
unicode-segmentation = "1.10"
sanitize-filename = "0.4"
percent-encoding = "2.2"
# reqwest = { version="0.11", features = ["stream"] }
# tokio = { version = "1", features = ["full"] }

[[bin]]
name = "termusic"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
termusic-lib= {path = "lib/"}
anyhow = "1.0"
base64 = "0.21"
clap = { version="4", features = ["derive"] }
# cpal = "0.13"
thiserror = "1.0.2"
dirs = "5.0"
discord-rich-presence = { version="0.2"}
figment = { version="0.10", features = ["toml"]}
glib = { version="0.17"  }
gstreamer = { version="0.20" }
hex = "0.4"
id3 = "1"
image = "0.24"
include_dir = "0.7"
lazy_static = "1.4"
# lexopt = "0.2"
libaes = "0.6"
libmpv-sys = { version = "3" }
# libmpv = { version = "2",  optional = true}
log = "0.4"
lovely_env_logger = "0.6"
lofty = "0.12"
md5 = "0.7"
num-bigint = "0.4"
pathdiff = { version = "0.2", features = ["camino"] }
pinyin = "0.9"
quick-xml = "0.28"
rand = "0.8"
regex = "^1.5.5"
rusqlite = { version = "0.29", features = ["bundled"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3"
souvlaki = { version = "0.6" }
symphonia = { version = "0.5.1",  features = ["aac","mp3","isomp4","alac"]}
# tempfile = { version = "3", optional = true}
toml = "0.7"
# tuirealm = { path = "../tui-realm", features = ["serialize"] }
# tui-realm-stdlib = {path = "../tui-realm-stdlib"}
# tui-realm-treeview = { path = "../tui-realm-treeview"}
tuirealm = { version = "1", features = ["serialize"] }
tui-realm-stdlib = "1"
tui-realm-treeview = "1"
unicode-width = "^0.1.8"
ureq = "2"
urlencoding = "2"
# viuer = { version = "0.6", features = ["sixel"] }
viuer = "0.6"
yaml-rust = "^0.4.5"
ytd-rs = { version = "0.1", features = ["yt-dlp"]}
walkdir = "2"
wildmatch = "2"
opml = "1"
chrono = "^0.4.23"
rss = "2"
rfc822_sanitizer = "0.3" 
ahash = "^0.8"
semver = "^1"
escaper = "0.1.1"
textwrap = "0.16"
bytes = "1"
unicode-segmentation = "1.10"
sanitize-filename = "0.4"
percent-encoding = "2.2"
# reqwest = { version="0.11", features = ["stream"] }
# tokio = { version = "1", features = ["full"] }

[features]
default = []
# left for debug
# default = ["gst"]
# default = ["mpv"]
# default = ["discord"]
# mpris = ["souvlaki"]
mpris = []
# cover = ["tempfile"]
cover = []
# gst = ["gstreamer","glib"]
gst = []
# mpv = ["libmpv-sys"]
mpv = []
# discord = ["discord-rich-presence"]
discord = []

[dev-dependencies]
pretty_assertions = "1"
# anyhow = "1"
# hound = "3.4"
# ringbuf = "0.3"
# clap = { version = "3.1", default-features = false, features = ["std"] }

[profile.release]
# lto = true
# panic = 'abort'
# opt-level = 'z'
# codegen-units = 1
